name: Auto Approve

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Check for approval from team members
        run: |
          TEAM_SLUG="maintainer"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          REPO="${{ github.repository }}"

          # チームメンバーのリストを取得
          MEMBERS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/orgs/{org_name}/teams/$TEAM_SLUG/members" | jq -r '.[].login')

          # プルリクエストのレビューコメントを取得
          COMMENTS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/comments" | jq -r '.[].user.login')

          # チームメンバーが承認コメントを残しているか確認
          for member in $MEMBERS; do
            if [[ "$COMMENTS" =~ "$member" ]]; then
              # 承認APIをコール
              curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/reviews" \
                -d '{"event":"APPROVE"}'
              break
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
