name: Auto Approve by Maintainer Team

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the reviewer is a team member and approved
        uses: actions/github-script@v6
        with:
          script: |
            if (context.payload.review.state !== "approved") {
              core.info("The review is not an approval. Exiting...");
              return;
            }

            const team_slug = "maintainer"; // ここに実際のチームスラグを設定
            const org = context.repo.owner; // ここに実際の組織名を設定

            async function isTeamMember(team_slug, username, org) {
              try {
                const response = await github.rest.teams.getMembershipForUserInOrg({
                  org: org,
                  team_slug: team_slug,
                  username: username,
                });
                return response.data.state === "active";
              } catch (error) {
                core.error(`Failed to fetch team membership for ${username} in ${team_slug} of ${org}: ` + error.message);
                return false;
              }
            }

            const reviewer = context.payload.review.user.login;
            isTeamMember(team_slug, reviewer, org).then(isMember => {
              if (isMember) {
                core.info(`${reviewer} is a team member and approved. Auto-approving the PR.`);
                github.rest.pulls.createReview({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.payload.pull_request.number,
                  event: "APPROVE",
                });
              } else {
                core.info(`${reviewer} is not a team member or the review is not an approval.`);
              }
            });
