name: Auto Approve

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Check membership
        id: check_membership
        uses: octokit/request-action@v2.x
        with:
          route: GET /orgs/{org}/teams/{team_slug}/memberships/{username}
          org: 'hiho-check-organization'
          team_slug: 'maintainer'
          username: ${{ github.event.review.user.login }}
          mediaType: '{"previews": ["hellcat"]}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-approve
        if: steps.check_membership.outputs.status == 'active'
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/pulls/{pull_number}/reviews
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pull_number: ${{ github.event.pull_request.number }}
          event: 'APPROVE'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} # Personal Access Token with repo scope
