name: Update README

on:
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Update README
        run: |
          echo -e "\nHoge" >> README.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Add 'Hoge' to README
          title: Add 'Hoge' to README
          body: This PR adds 'Hoge' to the README.
          branch: update-readme-${{ github.run_number }}
